package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// Building a TypeScript plugin.
//
// A TypeScript plugin ships as ONE compiled binary in its own directory and
// its manifest says `run: "./<id>-plugin"` — the shape a Go plugin has. That
// is not a style choice. Measured 2026-09-17 against the app's sandbox
// (docs/design/PLAN_SCAFFOLD_TRIALS.md): a shell wrapper cannot be exec'd, an
// interpreted `bun run` dies reading its ancestor directories, and Node on a
// loose bundle needs an lstat grant on them. A program in the plugin's own
// directory is what the exec rule already allows, and it resolves nothing at
// startup. The user installing the plugin needs no JavaScript runtime at all.
//
// The engine is chosen HERE, from the manifest, and the author never picks:
//
//   - Bun (`bun build --compile`) by default.
//   - A Node single-executable when the manifest declares `sockets.listen`.
//     Bun cannot serve an inherited listener fd, compiled or not — it reports
//     LISTENING and silently binds a different port (oven-sh/bun#22559). The
//     day that is fixed, the Node branch is deleted and nothing an author
//     sees changes.
//
// Both toolchains are the managed, pinned ones (runtime.go).

// postjectVersion pins the injector that writes the blob into the Node binary.
const postjectVersion = "1.0.0-alpha.6"

// seaFuse is the sentinel Node looks for to know a blob was injected. It is a
// constant of Node's single-executable feature, not a secret.
const seaFuse = "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2"

// tsBuildDir is the scratch directory inside the plugin. `plugin package`
// excludes it.
const tsBuildDir = ".branchkit-build"

// seaLoader is the CommonJS entry of a Node single-executable. Node requires
// that entry to be CommonJS, and a plugin is an ES module — the scaffold ends
// in a top-level `await plugin.run()`, which does not build as CommonJS. So
// the plugin is bundled as ESM, embedded as an asset, and imported from here.
// Authors write the same code for either engine.
const seaLoader = `// Generated by branchkit-cli. Do not edit.
const { getAsset } = require("node:sea");
const source = getAsset("plugin.mjs", "utf8");
import("data:text/javascript;base64," + Buffer.from(source).toString("base64")).catch((err) => {
  process.stderr.write("plugin failed to load: " + (err && err.stack ? err.stack : err) + "\n");
  process.exit(1);
});
`

type tsManifest struct {
	ID      string `json:"id"`
	Run     string `json:"run"`
	Sockets *struct {
		Listen []json.RawMessage `json:"listen"`
	} `json:"sockets"`
}

// tsEngine is the whole engine decision.
func tsEngine(m tsManifest) string {
	if m.Sockets != nil && len(m.Sockets.Listen) > 0 {
		return "node"
	}
	return "bun"
}

// tsOutputName validates `run` and returns the binary's file name. `run` must
// name a program in the plugin directory; anything else is a manifest from
// before plugins were compiled, and the error says what to write instead.
func tsOutputName(m tsManifest) (string, error) {
	want := "./" + m.ID + "-plugin"
	run := strings.TrimSpace(m.Run)
	words := strings.Fields(run)
	if len(words) != 1 || !strings.HasPrefix(run, "./") || strings.HasSuffix(run, ".sh") ||
		strings.ContainsAny(strings.TrimPrefix(run, "./"), `/\`) {
		return "", fmt.Errorf(
			"plugin.json `run` is %q, but a TypeScript plugin runs as a compiled binary in its own directory.\n"+
				"  Set \"run\": %q and add \"dev\": {\"build\": [[\"branchkit-cli\", \"dev\", \"build\"]], \"build_dir\": \".\"}.\n"+
				"  (A shell wrapper or `bun run …` cannot start under the plugin sandbox.)",
			m.Run, want)
	}
	return exeName(strings.TrimPrefix(run, "./")), nil
}

// tsEntry finds the plugin's entry module.
func tsEntry(absDir string) (string, error) {
	for _, rel := range []string{"src/index.ts", "index.ts", "src/main.ts"} {
		if fileExists(filepath.Join(absDir, rel)) {
			return rel, nil
		}
	}
	return "", fmt.Errorf("no entry module found — expected src/index.ts")
}

// bunEnv keeps Bun's package cache under the managed runtimes directory, so a
// build leaves nothing in the author's home directory.
func bunEnv() []string {
	return append(os.Environ(), "BUN_INSTALL_CACHE_DIR="+filepath.Join(runtimesDir(), "bun", "cache"))
}

func runTool(dir string, env []string, program string, args ...string) error {
	cmd := exec.Command(program, args...)
	cmd.Dir = dir
	cmd.Env = env
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// buildTypeScriptPlugin compiles the plugin in absDir to the binary its
// manifest names, and reports what it built.
func buildTypeScriptPlugin(absDir string) error {
	raw, err := os.ReadFile(filepath.Join(absDir, "plugin.json"))
	if err != nil {
		return fmt.Errorf("reading plugin.json: %w", err)
	}
	var m tsManifest
	if err := json.Unmarshal(raw, &m); err != nil {
		return fmt.Errorf("parsing plugin.json: %w", err)
	}
	outName, err := tsOutputName(m)
	if err != nil {
		return err
	}
	entry, err := tsEntry(absDir)
	if err != nil {
		return err
	}
	if err := ensureBunRuntime(); err != nil {
		return fmt.Errorf("the managed Bun toolchain is unavailable: %w", err)
	}
	bun := managedBunPath()

	pkgDir := absDir
	if !fileExists(filepath.Join(absDir, "package.json")) && fileExists(filepath.Join(absDir, "src", "package.json")) {
		pkgDir = filepath.Join(absDir, "src")
	}
	if !fileExists(filepath.Join(pkgDir, "node_modules")) {
		fmt.Printf("Installing dependencies for %s...\n", m.ID)
		if err := runTool(pkgDir, bunEnv(), bun, "install"); err != nil {
			return fmt.Errorf("bun install failed: %w", err)
		}
	}

	engine := tsEngine(m)
	out := filepath.Join(absDir, outName)
	// Build beside the target and rename over it: a running plugin keeps its
	// old inode, and nothing ever observes a half-written binary.
	tmp := filepath.Join(absDir, ".building-"+outName)
	os.Remove(tmp)
	defer os.Remove(tmp)

	switch engine {
	case "bun":
		fmt.Printf("Building TypeScript plugin %s (Bun %s)...\n", m.ID, bunVersion)
		err = buildWithBun(absDir, bun, entry, tmp)
	case "node":
		fmt.Printf("Building TypeScript plugin %s (Node %s — it declares sockets.listen, which Bun cannot serve)...\n", m.ID, nodeVersion)
		err = buildWithNode(absDir, bun, entry, tmp)
	}
	if err != nil {
		return err
	}
	if err := os.Chmod(tmp, 0o755); err != nil {
		return err
	}
	if err := os.Rename(tmp, out); err != nil {
		return err
	}
	size := int64(0)
	if info, err := os.Stat(out); err == nil {
		size = info.Size()
	}
	fmt.Printf("Built %s (%s engine, %d MB)\n", outName, engine, size/(1024*1024))
	return nil
}

// buildWithBun compiles a standalone Bun executable.
//
// The two --no-compile-autoload flags are REQUIRED, not tidiness. Without
// them the binary's startup autoload of `.env`/`bunfig.toml` fails inside the
// plugin sandbox and takes `process.env` with it, silently: the plugin runs
// with ZERO environment variables — no plugin id, no BRANCHKIT_PLUGIN_DIR, no
// LISTEN_FDS — and logs nothing about it.
func buildWithBun(absDir, bun, entry, out string) error {
	err := runTool(absDir, bunEnv(), bun, "build", entry,
		"--compile",
		"--no-compile-autoload-dotenv",
		"--no-compile-autoload-bunfig",
		"--outfile", out)
	if err != nil {
		return fmt.Errorf("bun build --compile failed: %w", err)
	}
	return nil
}

// buildWithNode produces a Node single-executable: bundle as ESM, embed it as
// an asset behind the CommonJS loader, generate the blob, and inject it into a
// copy of the managed Node binary.
func buildWithNode(absDir, bun, entry, out string) error {
	if err := ensureNodeRuntime(); err != nil {
		return fmt.Errorf("the managed Node toolchain is unavailable: %w", err)
	}
	node := managedNodePath()

	work := filepath.Join(absDir, tsBuildDir)
	if err := os.MkdirAll(work, 0o755); err != nil {
		return err
	}
	bundle := filepath.Join(work, "plugin.mjs")
	loader := filepath.Join(work, "main.cjs")
	blob := filepath.Join(work, "sea.blob")
	config := filepath.Join(work, "sea.json")

	// `--conditions=bun`: an SDK installed from source ships `src/` and no
	// `dist/`, and its package `exports` reach `src` only through the `bun`
	// condition. Without it a Node-target build cannot resolve the SDK.
	err := runTool(absDir, bunEnv(), bun, "build", entry,
		"--target=node", "--format=esm", "--conditions=bun", "--outfile", bundle)
	if err != nil {
		return fmt.Errorf("bundling for Node failed: %w", err)
	}
	if err := os.WriteFile(loader, []byte(seaLoader), 0o644); err != nil {
		return err
	}
	cfg, _ := json.Marshal(map[string]any{
		"main":                          loader,
		"output":                        blob,
		"disableExperimentalSEAWarning": true,
		"assets":                        map[string]string{"plugin.mjs": bundle},
	})
	if err := os.WriteFile(config, cfg, 0o644); err != nil {
		return err
	}
	if err := runTool(absDir, os.Environ(), node, "--experimental-sea-config", config); err != nil {
		return fmt.Errorf("generating the single-executable blob failed: %w", err)
	}

	if err := copyFile(node, out, 0o755); err != nil {
		return fmt.Errorf("copying the Node binary: %w", err)
	}
	// macOS: the copy carries Node's signature, which the injection
	// invalidates. Strip it first and ad-hoc sign after, or the kernel kills
	// the binary at launch.
	if runtime.GOOS == "darwin" {
		if err := runTool(absDir, os.Environ(), "codesign", "--remove-signature", out); err != nil {
			return fmt.Errorf("codesign --remove-signature failed: %w", err)
		}
	}
	inject := []string{"x", "postject@" + postjectVersion, out, "NODE_SEA_BLOB", blob, "--sentinel-fuse", seaFuse}
	if runtime.GOOS == "darwin" {
		inject = append(inject, "--macho-segment-name", "NODE_SEA")
	}
	if err := runTool(absDir, bunEnv(), bun, inject...); err != nil {
		return fmt.Errorf("injecting the blob failed: %w", err)
	}
	if runtime.GOOS == "darwin" {
		if err := runTool(absDir, os.Environ(), "codesign", "--sign", "-", out); err != nil {
			return fmt.Errorf("codesign failed: %w", err)
		}
	}
	return nil
}
