package main

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// The platform vocabulary a manifest can name, embedded so the static
// analyzer works in a third-party plugin's repo where `contracts/` does not
// exist. Generated by scripts/derive-cli-vocabulary.py from
// contracts/symbols.json; synced by `just contracts` and drift-gated by
// `just check-specs-synced`, the same way plugins/scripts carries
// method_privileges.json.
//
//go:embed manifest_vocabulary.json
var manifestVocabularyJSON []byte

type manifestVocabulary struct {
	APIVersion              string   `json:"api_version"`
	Privileges              []string `json:"privileges"`
	PluginMethods           []string `json:"plugin_methods"`
	PlatformCollections     []string `json:"platform_collections"`
	NonMethodImplementsKeys []string `json:"non_method_implements_keys"`
}

var vocabulary = loadVocabulary()

func loadVocabulary() manifestVocabulary {
	var v manifestVocabulary
	if err := json.Unmarshal(manifestVocabularyJSON, &v); err != nil {
		// Embedded and generated: a parse failure is a build-time defect,
		// not something a plugin author can cause or fix.
		panic(fmt.Sprintf("embedded manifest_vocabulary.json is invalid: %v", err))
	}
	return v
}

func inList(list []string, s string) bool {
	for _, item := range list {
		if item == s {
			return true
		}
	}
	return false
}

// nearest returns the closest name in `list` within a small edit distance,
// so a typo gets told what it probably meant. Empty when nothing is close —
// a wrong guess is worse than none.
func nearest(list []string, s string) string {
	best, bestDist := "", 0
	for _, cand := range list {
		d := editDistance(s, cand)
		// Scale tolerance with length: "priv" should not match "audio",
		// but "renderr_settings" should reach "render_settings".
		limit := 1 + len(cand)/6
		if d <= limit && (best == "" || d < bestDist) {
			best, bestDist = cand, d
		}
	}
	return best
}

func editDistance(a, b string) int {
	prev := make([]int, len(b)+1)
	cur := make([]int, len(b)+1)
	for j := range prev {
		prev[j] = j
	}
	for i := 1; i <= len(a); i++ {
		cur[0] = i
		for j := 1; j <= len(b); j++ {
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			cur[j] = min3(cur[j-1]+1, prev[j]+1, prev[j-1]+cost)
		}
		prev, cur = cur, prev
	}
	return prev[len(b)]
}

func min3(a, b, c int) int {
	if b < a {
		a = b
	}
	if c < a {
		a = c
	}
	return a
}

func didYouMean(list []string, s string) string {
	if n := nearest(list, s); n != "" {
		return fmt.Sprintf(" — did you mean %q?", n)
	}
	return ""
}

// checkImplementsMethods validates the method names in `implements`.
//
// This is the check §4.1 of DESIGN_PLUGIN_TEST_HARNESS.md asks for
// ("declared hooks match methods the actuator knows how to call"), and it
// earns its place because the failure is SILENT. `PluginImplements` in the
// actuator says it plainly: "Only methods the actuator KNOWS are
// dispatched. An unrecognized name is inert ... declaring one buys nothing
// and nothing will ever call it." A typo does not fail the load, does not
// warn, and does not appear in any log — the plugin simply never gets
// called. That has already cost this project a shipped bug.
func checkImplementsMethods(m map[string]any) []TestResult {
	impl, ok := m["implements"].(map[string]any)
	if !ok {
		return nil
	}
	known := append(append([]string{}, vocabulary.PluginMethods...),
		vocabulary.NonMethodImplementsKeys...)

	var names []string
	for name := range impl {
		names = append(names, name)
	}
	sort.Strings(names)

	var results []TestResult
	for _, name := range names {
		if inList(known, name) {
			continue
		}
		results = append(results, TestResult{
			Name:   "implements_" + name,
			Status: "fail",
			Detail: fmt.Sprintf(
				"%q is not a method the actuator calls%s — declaring it is inert: "+
					"nothing will ever invoke it, and nothing will say so at runtime. "+
					"Known: %s",
				name, didYouMean(known, name), strings.Join(known, ", ")),
		})
	}
	if len(results) == 0 && len(names) > 0 {
		return []TestResult{{
			Name: "implements", Status: "pass",
			Detail: fmt.Sprintf("%d declaration(s)", len(names)),
		}}
	}
	return results
}

// checkPrivilegeNames validates `privileges` and `optional_privileges`
// against the platform's privilege list.
//
// Both are checked, and deliberately by iterating one list rather than
// naming each field twice: the platform's own rule is that code touching
// grants iterates a registry instead of hand-enumerating the axes, because
// every axis added after a mechanism was written is one the mechanism
// forgets. An unknown privilege grants nothing, which is another silent
// outcome — the plugin runs and the call it needed is refused.
func checkPrivilegeNames(m map[string]any) []TestResult {
	var results []TestResult
	for _, field := range []string{"privileges", "optional_privileges"} {
		declared, ok := m[field].([]any)
		if !ok {
			continue
		}
		bad := 0
		for _, p := range declared {
			name, ok := p.(string)
			if !ok {
				results = append(results, TestResult{
					Name: field, Status: "fail",
					Detail: "entries must be strings",
				})
				bad++
				continue
			}
			if inList(vocabulary.Privileges, name) {
				continue
			}
			bad++
			results = append(results, TestResult{
				Name:   field + "_" + name,
				Status: "fail",
				Detail: fmt.Sprintf(
					"%q is not a privilege this platform defines%s — it grants nothing, "+
						"and the calls needing it are refused at runtime",
					name, didYouMean(vocabulary.Privileges, name)),
			})
		}
		if bad == 0 && len(declared) > 0 {
			results = append(results, TestResult{
				Name: field, Status: "pass",
				Detail: fmt.Sprintf("%d declared", len(declared)),
			})
		}
	}
	return results
}

// checkMinAPIVersion validates `min_api_version` against the API version
// this CLI was built against. A plugin asking for more than the platform
// provides is refused at load, so saying so here costs an install.
func checkMinAPIVersion(m map[string]any) []TestResult {
	raw, ok := m["min_api_version"]
	if !ok {
		return nil
	}
	declared, ok := raw.(string)
	if !ok {
		return []TestResult{{Name: "min_api_version", Status: "fail",
			Detail: "must be a string"}}
	}
	// semver.go already parses and orders these; no second implementation.
	want, ok := parseSemver(declared)
	if !ok {
		return []TestResult{{Name: "min_api_version", Status: "fail",
			Detail: fmt.Sprintf("%q is not a version (want major.minor.patch)", declared)}}
	}
	have, ok := parseSemver(vocabulary.APIVersion)
	if !ok {
		// The embedded value is generated; treat a bad one as a build defect
		// rather than blaming the manifest.
		return []TestResult{{Name: "min_api_version", Status: "warn",
			Detail: fmt.Sprintf("cannot compare: embedded api_version %q is malformed",
				vocabulary.APIVersion)}}
	}
	if !have.GreaterOrEqual(want) {
		return []TestResult{{Name: "min_api_version", Status: "fail",
			Detail: fmt.Sprintf(
				"requires API %s but this platform provides %s — it will be refused at load",
				declared, vocabulary.APIVersion)}}
	}
	return []TestResult{{Name: "min_api_version", Status: "pass",
		Detail: fmt.Sprintf("%s <= %s", declared, vocabulary.APIVersion)}}
}
